### ISSUE TITLE
Missing function in Team.py

### ISSUE THREAD

**Issue by jsego** [jsego/pacman-eutopia#15]
I get the following error when running the contest_manager locally:

```
Traceback (most recent call last):
  File "contest_manager.py", line 331, in <module>
    main()
  File "contest_manager.py", line 300, in main
    if new_match[0].get_loading_error() == False and new_match[1].get_loading_error() == False: 
AttributeError: 'Team' object has no attribute 'get_loading_error'
```

Any missing commit of the Team.py source code?

**Comment by jsego** [comment]
Solved in 83648fcf2d9e565ccbb5475d105f76b850cce676.
